import { date, timestamp, uuid } from 'drizzle-orm/pg-core';

// Shared column builders so every table follows DATABASE.md: UUID primary keys generated by the
// database, and timestamptz timestamps.
export const primaryId = () => uuid('id').primaryKey().defaultRandom();

export const createdAt = () => timestamp('created_at', { withTimezone: true }).notNull().defaultNow();

// `updated_at` is kept current by a database trigger attached with each table's migration, not by application code.
export const updatedAt = () => timestamp('updated_at', { withTimezone: true }).notNull().defaultNow();

// timestamptz and calendar-date builders. Dates are strings, so a time zone can never shift them.
export const tstz = (name: string) => timestamp(name, { withTimezone: true });
export const dateStr = (name: string) => date(name, { mode: 'string' });
